name: Check spelling

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  main:
    - name: Install Aspell
      shell: bash
      run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y aspell aspell-en
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install aspell
          fi

    - name: Check Typos
      shell: bash
      run: |
          if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
            composer test:typos
          fi
